// <auto-generated />
namespace ModelShopOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShopOnline_b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShopOnline_b));
        
        string IMigrationMetadata.Id
        {
            get { return "201806051334009_ShopOnline_b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
